modules/wiki/controllers/ArticuloCambioController.php
<?php

namespace app\modules\wiki\controllers;
use Yii;
use app\models\Articulo;
use app\models\ArticuloCambio;
use app\models\Proyecto;
use app\models\Log;
use app\modules\wiki\models\ArticuloCambioSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;

/**
 * ArticuloCambioController implements the CRUD actions for ArticuloCambio model.
 */
class ArticuloCambioController extends Controller
{
    public function behaviors()
    {
		return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['update', 'delete', 'create','index','view'],
                'rules' => [

                    [
                        'actions' => ['index','view','update','delete', 'create'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all ArticuloCambio models.
     * @return mixed
     */
    public function actionIndex($idArticulo,$idProyecto)
    {
    	$model = Proyecto::findOne($idProyecto);
    	if (!Yii::$app->user->can('usuarioVinculadoProyecto', ['Proyecto' => $model])) {
    		throw new ForbiddenHttpException('El usuario no esta vinculado al Proyecto');
    	}
        $searchModel = new ArticuloCambioSearch;
        
        $searchModel->idArticulo=$idArticulo;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
        $articulos= Articulo::findOne($idArticulo);     
        $articulo=  Log::findOne($idArticulo);
        $proyecto=  Proyecto::findOne($idProyecto);

        
        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,
        	'idArticulo'=>$articulo,
       		'proyecto'=>$proyecto,
        	'articulos'=>$articulos,
        ]);
    }

    /**
     * Displays a single ArticuloCambio model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new ArticuloCambio model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new ArticuloCambio;

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idLog]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing ArticuloCambio model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idLog]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing ArticuloCambio model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the ArticuloCambio model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return ArticuloCambio the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = ArticuloCambio::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

modules/wiki/controllers/ArticuloController.php
<?php

namespace app\modules\wiki\controllers;
use Yii;
use app\models\Articulo;
use app\models\Proyecto;
use app\models\Usuario;
use app\modules\wiki\models\ArticuloSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\web\ForbiddenHttpException;

/**
 * ArticuloController implements the CRUD actions for Articulo model.
 */
class ArticuloController extends Controller
{
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Articulo models.
     * @return mixed
     */
    public function actionIndex($idProyecto)
    {
    	$model = Proyecto::findOne($idProyecto);
    	if (!Yii::$app->user->can('usuarioVinculadoProyecto', ['Proyecto' => $model])) {
    		throw new ForbiddenHttpException('El usuario no esta vinculado al Proyecto');
    	}
    	
        $searchModel = new ArticuloSearch;
        $searchModel->idProyecto=$idProyecto;
        $dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());
        $proyecto=  Proyecto::findOne($idProyecto);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel,'proyecto'=>$proyecto,
        ]);
    }

    /**
     * Displays a single Articulo model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    
    protected function crearUsuario($idArticulo) {
    	$model = new Articulo;
    	$model->idArticulo = $idArticulo;
    	$post = Yii::$app->request->post();
    	print_r($post);
    	//exit;
    	//$var = $model->find()->where('idEtapa=:idEtapa and idUsuario=:idUsuario',[':idEtapa'=>$idEtapa, ':idUsuario'=>$post['RecursoProyecto']['idUsuario']])->all();
    	if ($model->load(Yii::$app->request->post()) && ($model->findOne(['idArticulo'=>$idArticulo, 'idUsuario'=>$post['Articulo']['idUsuario']]) ||  $model->save() )) {
    		//flash
    	}
    	return $model;
    }  
    
    
    
    
    /**
     * Creates a new Articulo model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($id)
    {
        $model = new Articulo();
        $model ->idProyecto=$id;
        $model ->fecha=date('Y-m-d H:i:s');
        $model ->fechaAlta=date('Y-m-d H:i:s');
        $model ->idUsuario=Yii::$app->user->getId();
        
		$proyecto= Proyecto::findOne($id);
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idArticulo]);
        } else {
            return $this->render('create', [
                'model' => $model,
           		'proyecto' =>$proyecto,
            ]);
        }
    }

    /**
     * Updates an existing Articulo model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);
        $model ->fechaAlta=date('Y-m-d H:i:s');

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->idArticulo]);
        } else {
            return $this->render('update', [
                'model' => $model,
            	'proyecto' => $model->idProyecto0,
            ]);
        }
    }

    /**
     * Deletes an existing Articulo model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    

    public function actionDelete($id,$idProyecto)
    {
    	$this->findModel($id)->delete();
    
    	return $this->redirect(['/wiki/articulo', 'idProyecto' => $idProyecto]);
    }
    /**
    public function actionDelete($id,$idProyecto)
    {   $unLogs = new Log();
        if (($unLogs= Log::find($id)) == null) {
        	$this->findModel($id)->delete();
        	} else {
        		return $this->redirect(['/proyecto/view', 'id' => $idProyecto]);        		
        	}
        	throw new NotFoundHttpException('No es posible eliminar este Articulo. Primero elimine los Logs asociados a el.');
            }*/

    /**
     * Finds the Articulo model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Articulo the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Articulo::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('El articulo no existe');
        }
    }
}

modules/wiki/views/articulo/_form.php
<!DOCTYPE html>
<html>
<head><!-- CDN hosted by Cachefly -->
<script src="//tinymce.cachefly.net/4.0/tinymce.min.js"></script>
<script>
        tinymce.init({selector:'textarea'});
</script>
</head>

<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\Articulo $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="articulo-form">

    <?php $form = ActiveForm::begin(); ?>

    <?php // $form->field($model, 'idProyecto')->textInput(['value'=> $model->idProyecto]) ?>

    <?= $form->field($model, 'titulo')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'texto')->textarea(['rows' => 6]) ?>

    <?php //  $form->field($model, 'fechaAlta')->textInput(['value'=>date("Y-m-d H:i:s")]) ?>

    <?php //  $form->field($model, 'fecha')->textInput(['value'=>date("Y-m-d H:i:s")]) ?>

    <?php // $form->field($model, 'idUsuario')->textInput(['value'=> Yii::$app->user->identity->id]) ?>


    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Crear' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
</html>

modules/wiki/views/articulo/_formUpdate.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\models\Articulo $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="articulo-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'titulo')->textInput(['maxlength' => 255]) ?>

    <?= $form->field($model, 'texto')->textarea(['rows' => 6]) ?>

    <?= $form->field($model, 'fechaAlta')->textInput() ?>

    <?= $form->field($model, 'fecha')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

modules/wiki/views/articulo/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/**
 * @var yii\web\View $this
 * @var app\modules\wiki\models\ArticuloSearch $model
 * @var yii\widgets\ActiveForm $form
 */
?>

<div class="articulo-search">

<div style="float: right; margin-right: -550px;" class="form-inline">	
    <?php $form = ActiveForm::begin([
        'method' => 'get',
    ]); ?>
    <?= $form->field($model, 'texto')->label('Buscador') ?><span class="glyphicon glyphicon-search"></span></div>
    <?php // $form->field($model, 'idArticulo') ?>

    <?php // $form->field($model, 'idProyecto') ?>

    <?php // $form->field($model, 'fechaAlta') ?>

    <?php // echo $form->field($model, 'fecha') ?>

    <?php // echo $form->field($model, 'idUsuario') ?>

    <?php ActiveForm::end(); ?>

</div>

modules/wiki/views/articulo/_view.php
<?php
use yii\helpers\Html;
/* @var $this NoticiaController */
/* @var $model Noticia */
?>
<div class="col-md-12 ">
        <h3><?php echo Html::encode($model->titulo); ?></h3>
        <?php echo $model->texto; ?>
        <br><button>Realizar comentario</button><hr>
</div>

modules/wiki/views/articulo/create.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Articulo $model
 */

$this->title = 'Crear Nuevo Articulo';
$this->params['breadcrumbs'][] = ['label' => 'Proyectos', 'url' => ['/proyecto/index']];
$this->params['breadcrumbs'][] = ['label' => $proyecto->Proyecto, 'url' => ['/proyecto/view','id'=>$proyecto->id]];
$this->params['breadcrumbs'][] = ['label' => 'Articulos', 'url' => ['index','idProyecto'=>$proyecto->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="articulo-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/wiki/views/articulo/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\ListView;
use app\widgets\NuestroNav;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\modules\wiki\models\ArticuloSearch $searchModel
 */

$this->title = 'Articulos';
$this->params['breadcrumbs'][] = ['label' => 'Proyectos', 'url' => ['/proyecto/index']];
$this->params['breadcrumbs'][] = ['label' => $proyecto->Proyecto, 'url' => ['/proyecto/view','id'=>$proyecto->id]];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="articulo-index">
	<?= NuestroNav::widget(['idProyecto'=>$proyecto->id]); ?>
    <h1><?= Html::encode($this->title) ?></h1>

    <?php echo $this->render('_search', ['model' => $searchModel],$proyecto->id); ?>

    <p>
        <?= Html::a('Crear Nuevo Articulo', ['create','id'=>$proyecto->id], ['class' => 'btn btn-success']) ?>
    
    </p>          
    
    <?= ListView::widget([
    	'dataProvider' => $dataProvider,
        'itemView'=>'view',
    ]); ?>

</div>

modules/wiki/views/articulo/update.php
<?php

use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\Articulo $model
 */

$this->title = 'Update Articulo: ' . $model->idArticulo;
$this->params['breadcrumbs'][] = ['label' => 'Proyectos', 'url' => ['/proyecto/index']];
$this->params['breadcrumbs'][] = ['label' => $proyecto->Proyecto, 'url' => ['/proyecto/view','id'=>$proyecto->id]];
$this->params['breadcrumbs'][] = ['label' => 'Articulos', 'url' => ['index','idProyecto'=>$proyecto->id]];
$this->params['breadcrumbs'][] = ['label' => $model->titulo, 'url' => ['view', 'id' => $model->idArticulo]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="articulo-update">


    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

modules/wiki/views/articulo/view.php
<?php
use yii\helpers\Html;

use yii\bootstrap\Modal;
/* @var $this NoticiaController */
/* @var $model Noticia */
?>
<div class="col-md-12 ">
		<h3><?php echo Html::encode($model->titulo); ?></h3>
        <?php echo $model->texto.'<br>'; ?>
        
        <?php   
               
        Modal::begin([
            'header' => '<h3>'.$model->titulo.'</h3>'.$model->idUsuario0->NombreApellido,
            'toggleButton' => ['label' => 'Ver Articulo'],
            'footer' =>'Fecha De Alta(ultima actualizacion):  '.$model->fechaAlta.'<br>Fecha:  '.$model->fecha.'<br><hr>'.Html::a('<span class="glyphicon glyphicon-header"></span>', ['articulo-cambio/index', 'idArticulo' => $model->idArticulo, 'idProyecto'=>$model->idProyecto], ['class' => 'btn btn-success', 'data'=>['method' => 'post']]).Html::a('<span class="glyphicon glyphicon-trash"></span>', ['delete', 'id' => $model->idArticulo, 'idProyecto'=>$model->idProyecto], ['class' => 'btn btn-danger', 'data'=>['method' => 'post']]).Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['update', 'id' => $model->idArticulo], ['class' => 'btn btn-primary']).'<button type="button" class="btn btn-warning" data-dismiss="modal"><span class="glyphicon glyphicon-remove"></span></button>',
            'options' => ['style' => 'background-color:rgba(0,0,0,0.2);'],        
        ]);        
        echo $model->texto;
        Modal::end();
        echo '<hr>';
        ?>
        
</div>